apiVersion: v2
name: kronos
description: KronosCore Operator Helm Chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.3.1"

icon: https://kronosorg.github.io/kronos-chart/kronos_logo.png

annotations: 
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: kronos-core
      image: kronosorg/kronos-core:v0.3.1
      platforms:
        - linux/amd64 
  artifacthub.io/crds: |
    - kind: KronosApp
      version: core.wecraft.tn/v1alpha1
      name: kronosapp
      displayName: kronosApp
      description: The Kronos-Core Custom Resource Definition (CRD) allows users to define resource schedules for their Kubernetes clusters. The CRD manifest includes several fields that users can configure to customize their resource schedules.    
  artifacthub.io/crdsExamples: |
    - apiVersion: core.wecraft.tn/v1alpha1
      kind: KronosApp
      metadata:
        name: dev-scheduling
      spec:
        startSleep: "18:00"
        endSleep: "07:00"
        weekdays: "1-5"
        timezone: "Africa/Tunis"
        includedObjects: 
          - apiVersion: "apps/v1"
            kind: "*"
            namespace: "frontend"
            includeRef: "dev.*"
            excludeRef: ""  
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: kronos-docs
      url: https://kronosorg.github.io/kronos-docs/
    - name: kronos-github
      url: https://github.com/KronosOrg/kronos-core  
  artifacthub.io/maintainers: |
    - name: IsmailAbdelkefi
      email: abdelkefi.ismail@pm.me  
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack    