apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: kronos
  name: kronos-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kronos-leader-election-role
subjects:
- kind: ServiceAccount
  name: kronos-controller-manager
  namespace: {{ .Release.Namespace }}