apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kronos-serving-cert
  labels:
    app: kronos
  name: kronos-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kronos-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-core-wecraft-tn-v1alpha1-kronosapp
  failurePolicy: Fail
  name: vkronosapp.kb.io
  rules:
  - apiGroups:
    - core.wecraft.tn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kronosapps
  sideEffects: None