apiVersion: v1
kind: Service
metadata:
  labels:
    app: kronos
    control-plane: controller-manager
  name: kronos-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager