apiVersion: v1
kind: Service
metadata:
  labels:
    app: kronos
  name: kronos-controller-manager-metrics-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: kronos
    control-plane: controller-manager

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kronos
  name: kronos-webhook-service
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: kronos
    control-plane: controller-manager